### ISSUE TITLE
[Bug] KOC_FORCE_SERVER_DOWNLOAD is an invalid type

### ISSUE THREAD

**Issue by RisedSky** [kocxyz/ServerDocker#1]
services.server.environment.KOC_FORCE_SERVER_DOWNLOAD contains true, which is an invalid type, it should be a string, number, or a null

Changing to 
```docker
KOC_FORCE_SERVER_DOWNLOAD: "true"
```
fix it

**Comment by RisedSky** [comment]
Also, you forgot to add the version of docker-compose.yml at the top

**Comment by Tandashi** [comment]
Forgot to mention in the README so will add that later but the you need a docker version that supports compose v2.
https://kocity.xyz/docs/hosting/docker#prequisite

Since compose v1 (the one that requires a version at the top etc.) has officially been deprecated.
> Compose V1 no longer receives updates and will not be available in new releases of Docker Desktop after June 2023.
> Compose V2 is included with all currently supported versions of Docker Desktop. For more information, see [Migrate to > Compose V2](https://docs.docker.com/compose/migrate).

https://docs.docker.com/compose/
